spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/sprinkle?useSSL=false
    username: root
    password: mysql
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect